print(" ANANDHU V POOVANKAL\n 23MCA015")
import numpy as np
arr_1d=np.array([1,2,3,4,5])
dignl_mtrx_1d=np.diag(arr_1d)
print("1D Array:\n",arr_1d)
print("Diagonal of 1D Matrix:\n",dignl_mtrx_1d)
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
dignal_mtrx_2d=np.diag(arr_2d)
print("2D Array:\n",arr_2d)
print("Diagonal of 2D Matrix:\n",dignal_mtrx_2d)
arr_2d_non=np.array([[1,2,3],[4,5,6]])
dignl_mtrx_non_2d=np.diag(arr_2d_non)
print("2D Non Square Matrix:\n",arr_2d_non)
print("Diagonal Elements of 2D Non Square Matrix:\n",dignl_mtrx_non_2d)